#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  uninstall-gitnexus.sh — One-command GitNexus teardown for fullstack projects
#
#  Usage (run from project root):
#    bash uninstall-gitnexus.sh
#
#  What this script does (reverse of install):
#    1. Remove <!--gitnexus-->...<!--gitnexus:end--> block from CLAUDE.md
#    2. Remove project skills (generated by gitnexus analyze)
#    3. Remove project hook JS + clean hook entries from settings.json
#    4. Restore hooks: .claude/settings.json -> ~/.claude/settings.json
#    5. Restore MCP config: .mcp.json -> ~/.mcp.json
#    6. Remove .gitnexus knowledge graph
#    7. Remove AGENTS.md + cleanup empty .claude directories
#    8. Uninstall gitnexus globally
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

# ── Colors ───────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BOLD='\033[1m'; NC='\033[0m'

ok()   { echo -e "${GREEN}  ✓${NC} $1"; }
warn() { echo -e "${YELLOW}  ⚠${NC}  $1"; }
die()  { echo -e "${RED}  ✗${NC} $1"; exit 1; }
step() { echo -e "\n${BOLD}── Step $1 ──────────────────────────────────────${NC}"; }

# ── Paths ─────────────────────────────────────────────────────────────────────
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
GLOBAL_MCP="$HOME/.mcp.json"
GLOBAL_SETTINGS="$HOME/.claude/settings.json"
GLOBAL_SKILLS_DIR="$HOME/.claude/skills/gitnexus"
GLOBAL_HOOK_DIR="$HOME/.claude/hooks/gitnexus"

PROJECT_MCP="$PROJECT_ROOT/.mcp.json"
PROJECT_CLAUDE_DIR="$PROJECT_ROOT/.claude"
PROJECT_SETTINGS="$PROJECT_CLAUDE_DIR/settings.json"
PROJECT_HOOK_DIR="$PROJECT_CLAUDE_DIR/hooks/gitnexus"
PROJECT_HOOK_FILE="$PROJECT_HOOK_DIR/gitnexus-hook.cjs"
PROJECT_SKILLS_DIR="$PROJECT_CLAUDE_DIR/skills/gitnexus"
PROJECT_GITNEXUS="$PROJECT_ROOT/.gitnexus"
CLAUDE_MD="$PROJECT_ROOT/CLAUDE.md"
AGENTS_MD="$PROJECT_ROOT/AGENTS.md"

echo -e "\n${BOLD}GitNexus Uninstall${NC} — ${PROJECT_ROOT}\n"

# ─────────────────────────────────────────────────────────────────────────────
step "1/8 — Remove <!--gitnexus-->...<!--gitnexus:end--> block from CLAUDE.md"
# ─────────────────────────────────────────────────────────────────────────────
if [[ -f "$CLAUDE_MD" ]] && grep -q "<!--gitnexus-->" "$CLAUDE_MD"; then
  # Xoa tu dong chua <!--gitnexus--> den dong chua <!--gitnexus:end--> (inclusive)
  sed -i '/<!--gitnexus-->/,/<!--gitnexus:end-->/d' "$CLAUDE_MD"
  ok "gitnexus block removed from CLAUDE.md"
else
  warn "gitnexus block not found in CLAUDE.md -- skipping"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "2/8 — Remove project skills"
# ─────────────────────────────────────────────────────────────────────────────
if [[ -d "$PROJECT_SKILLS_DIR" ]]; then
  rm -rf "$PROJECT_SKILLS_DIR"
  ok "Project skills removed: $PROJECT_SKILLS_DIR"
else
  warn "Project skills not found -- skipping"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "3/8 — Remove project hook JS + clean hook entries from settings.json"
# ─────────────────────────────────────────────────────────────────────────────
if [[ -f "$PROJECT_HOOK_FILE" ]]; then
  rm -f "$PROJECT_HOOK_FILE"
  ok "Hook file removed: $PROJECT_HOOK_FILE"
else
  warn "Hook file not found -- skipping"
fi

if [[ -f "$PROJECT_SETTINGS" ]]; then
  # Xoa cac hook entry co command chua "gitnexus-hook.cjs"
  jq 'del(.hooks.PreToolUse[]  | select(.hooks[]?.command | test("gitnexus-hook\\.cjs"; "i")))
    | del(.hooks.PostToolUse[] | select(.hooks[]?.command | test("gitnexus-hook\\.cjs"; "i")))' \
    "$PROJECT_SETTINGS" > "$PROJECT_SETTINGS.tmp" \
    && mv "$PROJECT_SETTINGS.tmp" "$PROJECT_SETTINGS"
  ok "Hook entries removed from $PROJECT_SETTINGS"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "4/8 — Restore hooks: .claude/settings.json -> ~/.claude/settings.json"
# ─────────────────────────────────────────────────────────────────────────────
if [[ ! -f "$PROJECT_SETTINGS" ]]; then
  warn ".claude/settings.json not found -- skipping hook restore"
else
  # Lay cac gitnexus hook con lai trong project settings
  GITNEXUS_HOOKS=$(jq '{
    "PreToolUse":  (.hooks.PreToolUse  // [] | map(select(.hooks[]?.command | test("gitnexus"; "i")))),
    "PostToolUse": (.hooks.PostToolUse // [] | map(select(.hooks[]?.command | test("gitnexus"; "i"))))
  }' "$PROJECT_SETTINGS")

  PRE_COUNT=$(echo "$GITNEXUS_HOOKS"  | jq '.PreToolUse  | length')
  POST_COUNT=$(echo "$GITNEXUS_HOOKS" | jq '.PostToolUse | length')

  if [[ "$PRE_COUNT" -gt 0 || "$POST_COUNT" -gt 0 ]]; then
    mkdir -p "$(dirname "$GLOBAL_SETTINGS")"

    if [[ -f "$GLOBAL_SETTINGS" ]]; then
      jq -s '
        .[0] as $global | .[1] as $gn |
        $global * {
          "hooks": {
            "PreToolUse":  (($global.hooks.PreToolUse  // []) + ($gn.PreToolUse  // []) | unique_by(.matcher)),
            "PostToolUse": (($global.hooks.PostToolUse // []) + ($gn.PostToolUse // []) | unique_by(.matcher))
          }
        }
      ' "$GLOBAL_SETTINGS" <(echo "$GITNEXUS_HOOKS") > "$GLOBAL_SETTINGS.tmp" \
        && mv "$GLOBAL_SETTINGS.tmp" "$GLOBAL_SETTINGS"
    else
      echo "{\"hooks\": $GITNEXUS_HOOKS}" | jq '.' > "$GLOBAL_SETTINGS"
    fi
    ok "Hooks restored to $GLOBAL_SETTINGS"
  else
    warn "No gitnexus hooks in project settings -- nothing to restore"
  fi

  # Xoa tat ca gitnexus hooks khoi project settings
  jq 'del(.hooks.PreToolUse[]  | select(.hooks[]?.command | test("gitnexus"; "i")))
    | del(.hooks.PostToolUse[] | select(.hooks[]?.command | test("gitnexus"; "i")))' \
    "$PROJECT_SETTINGS" > "$PROJECT_SETTINGS.tmp" \
    && mv "$PROJECT_SETTINGS.tmp" "$PROJECT_SETTINGS"

  # Neu project settings gio rong thi xoa luon
  PRE_LEFT=$(jq '.hooks.PreToolUse  // [] | length' "$PROJECT_SETTINGS")
  POST_LEFT=$(jq '.hooks.PostToolUse // [] | length' "$PROJECT_SETTINGS")
  if [[ "$PRE_LEFT" -eq 0 && "$POST_LEFT" -eq 0 ]]; then
    rm -f "$PROJECT_SETTINGS"
    ok "Project settings.json empty -- removed"
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
step "5/8 — Restore MCP config: .mcp.json -> ~/.mcp.json"
# ─────────────────────────────────────────────────────────────────────────────
if [[ ! -f "$PROJECT_MCP" ]]; then
  warn ".mcp.json not found -- skipping MCP restore"
else
  HAS_GITNEXUS=$(jq 'has("mcpServers") and (.mcpServers | has("gitnexus"))' "$PROJECT_MCP")
  if [[ "$HAS_GITNEXUS" == "true" ]]; then
    # Khoi phuc ve global voi command npx (nhu truoc khi install)
    EXISTING_GLOBAL="{}"
    [[ -f "$GLOBAL_MCP" ]] && EXISTING_GLOBAL=$(cat "$GLOBAL_MCP")

    jq -n \
      --argjson existing "$EXISTING_GLOBAL" \
      '$existing * {"mcpServers": {"gitnexus": {"command": "npx", "args": ["-y", "gitnexus@1.5.3", "mcp"]}}}' \
      > "$GLOBAL_MCP"
    ok "gitnexus MCP entry restored to $GLOBAL_MCP"

    # Xoa gitnexus khoi project .mcp.json
    jq 'del(.mcpServers.gitnexus)' "$PROJECT_MCP" > "$PROJECT_MCP.tmp" \
      && mv "$PROJECT_MCP.tmp" "$PROJECT_MCP"

    # Neu project .mcp.json gio rong thi xoa
    REMAINING=$(jq '.mcpServers | length' "$PROJECT_MCP")
    if [[ "$REMAINING" -eq 0 ]]; then
      rm -f "$PROJECT_MCP"
      ok "Project .mcp.json empty -- removed"
    else
      ok "gitnexus entry removed from project .mcp.json"
    fi
  else
    warn "No gitnexus entry in .mcp.json -- skipping"
  fi
fi

# ─────────────────────────────────────────────────────────────────────────────
step "6/8 — Remove .gitnexus knowledge graph"
# ─────────────────────────────────────────────────────────────────────────────
if [[ -d "$PROJECT_GITNEXUS" ]]; then
  rm -rf "$PROJECT_GITNEXUS"
  ok "Knowledge graph removed: $PROJECT_GITNEXUS"
else
  warn ".gitnexus not found -- already removed or never created"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "7/8 — Remove AGENTS.md + cleanup empty .claude directories"
# ─────────────────────────────────────────────────────────────────────────────
if [[ -f "$AGENTS_MD" ]]; then
  rm -f "$AGENTS_MD"
  ok "AGENTS.md removed"
else
  warn "AGENTS.md not found -- skipping"
fi

# Xoa thu muc hook neu rong
[[ -d "$PROJECT_HOOK_DIR" ]] && rmdir --ignore-fail-on-non-empty "$PROJECT_HOOK_DIR" 2>/dev/null || true

# Xoa .claude neu hoan toan rong
if [[ -d "$PROJECT_CLAUDE_DIR" ]] && [[ -z "$(ls -A "$PROJECT_CLAUDE_DIR" 2>/dev/null)" ]]; then
  rmdir "$PROJECT_CLAUDE_DIR"
  ok "Empty .claude directory removed"
elif [[ -d "$PROJECT_CLAUDE_DIR" ]]; then
  warn ".claude directory has other content -- kept"
fi

# ─────────────────────────────────────────────────────────────────────────────
step "8/8 — Uninstall gitnexus globally"
# ─────────────────────────────────────────────────────────────────────────────
if command -v gitnexus >/dev/null 2>&1; then
  npm uninstall -g gitnexus
  ok "gitnexus uninstalled globally"
else
  warn "gitnexus not found in PATH -- already uninstalled"
fi

# Xoa global hook dir neu con ton tai
[[ -d "$GLOBAL_HOOK_DIR" ]]   && rm -rf "$GLOBAL_HOOK_DIR"   && ok "Global hook directory removed"   || true
[[ -d "$GLOBAL_SKILLS_DIR" ]] && rm -rf "$GLOBAL_SKILLS_DIR" && ok "Global skills directory removed" || true

# ─────────────────────────────────────────────────────────────────────────────
echo -e "\n${GREEN}${BOLD}═══════════════════════════════════════════════${NC}"
echo -e "${GREEN}${BOLD}  GitNexus uninstall complete!${NC}"
echo -e "${GREEN}${BOLD}═══════════════════════════════════════════════${NC}"
echo ""
echo "  Removed:"
echo "    - <!--gitnexus--> block in CLAUDE.md"
echo "    - .gitnexus knowledge graph"
echo "    - .claude/hooks/gitnexus/gitnexus-hook.cjs"
echo "    - Project MCP + hook entries"
echo "    - AGENTS.md"
echo "    - gitnexus npm global package"
echo ""
echo -e "  ${YELLOW}Next step:${NC} Restart Claude Code to unload MCP server."
echo ""
