# =============================================================================
#  uninstall-gitnexus.ps1 — One-command GitNexus teardown for fullstack projects
#
#  Usage (run from project root):
#    powershell -ExecutionPolicy Bypass -File uninstall-gitnexus.ps1
#
#  What this script does (reverse of install):
#    1. Remove <!--gitnexus-->...<!--gitnexus:end--> block from CLAUDE.md
#    2. Remove project skills (generated by gitnexus analyze)
#    3. Remove project hook JS + clean hook entries from settings.json
#    4. Restore hooks: .claude\settings.json -> ~\.claude\settings.json
#    5. Restore MCP config: .mcp.json -> ~\.mcp.json
#    6. Remove .gitnexus knowledge graph
#    7. Remove AGENTS.md + cleanup empty .claude directories
#    8. Uninstall gitnexus globally
# =============================================================================

#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

# ── Colors / Logging ──────────────────────────────────────────────────────────
function ok   { param($msg) Write-Host "  v $msg"  -ForegroundColor Green }
function warn { param($msg) Write-Host "  ! $msg"  -ForegroundColor Yellow }
function die  { param($msg) Write-Host "  x $msg"  -ForegroundColor Red; exit 1 }
function step { param($msg) Write-Host "`n-- $msg ----------------------------------" -ForegroundColor White }

# ── Paths ─────────────────────────────────────────────────────────────────────
$PROJECT_ROOT       = $PSScriptRoot
if (-not $PROJECT_ROOT) { $PROJECT_ROOT = (Get-Location).Path }

$GLOBAL_MCP         = Join-Path $env:USERPROFILE ".mcp.json"
$GLOBAL_SETTINGS    = Join-Path $env:USERPROFILE ".claude\settings.json"
$GLOBAL_SKILLS_DIR  = Join-Path $env:USERPROFILE ".claude\skills\gitnexus"
$GLOBAL_HOOK_DIR    = Join-Path $env:USERPROFILE ".claude\hooks\gitnexus"

$PROJECT_MCP        = Join-Path $PROJECT_ROOT ".mcp.json"
$PROJECT_CLAUDE_DIR = Join-Path $PROJECT_ROOT ".claude"
$PROJECT_SETTINGS   = Join-Path $PROJECT_CLAUDE_DIR "settings.json"
$PROJECT_HOOK_DIR   = Join-Path $PROJECT_CLAUDE_DIR "hooks\gitnexus"
$PROJECT_HOOK_FILE  = Join-Path $PROJECT_HOOK_DIR "gitnexus-hook.cjs"
$PROJECT_SKILLS_DIR = Join-Path $PROJECT_CLAUDE_DIR "skills\gitnexus"
$PROJECT_GITNEXUS   = Join-Path $PROJECT_ROOT ".gitnexus"
$CLAUDE_MD          = Join-Path $PROJECT_ROOT "CLAUDE.md"
$AGENTS_MD          = Join-Path $PROJECT_ROOT "AGENTS.md"

Write-Host "`nGitNexus Uninstall -- $PROJECT_ROOT`n" -ForegroundColor Cyan

# =============================================================================
step "1/8 -- Remove <!--gitnexus-->...<!--gitnexus:end--> block from CLAUDE.md"
# =============================================================================
if (Test-Path $CLAUDE_MD) {
    $content = Get-Content $CLAUDE_MD -Raw
    if ($content -match '<!--gitnexus-->') {
        # Xoa toan bo block tu <!--gitnexus--> den <!--gitnexus:end--> (inclusive, multiline)
        $cleaned = [regex]::Replace($content, '(?s)\r?\n?<!--gitnexus-->.*?<!--gitnexus:end-->\r?\n?', "`n")
        $cleaned.TrimEnd() | Set-Content $CLAUDE_MD -Encoding UTF8 -NoNewline
        ok "gitnexus block removed from CLAUDE.md"
    } else {
        warn "gitnexus block not found in CLAUDE.md -- skipping"
    }
} else {
    warn "CLAUDE.md not found -- skipping"
}

# =============================================================================
step "2/8 -- Remove project skills"
# =============================================================================
if (Test-Path $PROJECT_SKILLS_DIR) {
    Remove-Item -Recurse -Force $PROJECT_SKILLS_DIR
    ok "Project skills removed: $PROJECT_SKILLS_DIR"
} else {
    warn "Project skills not found -- skipping"
}

# =============================================================================
step "3/8 -- Remove project hook JS + clean hook entries from settings.json"
# =============================================================================
if (Test-Path $PROJECT_HOOK_FILE) {
    Remove-Item -Force $PROJECT_HOOK_FILE
    ok "Hook file removed: $PROJECT_HOOK_FILE"
} else {
    warn "Hook file not found -- skipping"
}

if (Test-Path $PROJECT_SETTINGS) {
    $settingsObj = Get-Content $PROJECT_SETTINGS -Raw | ConvertFrom-Json -AsHashtable
    foreach ($hookType in @('PreToolUse', 'PostToolUse')) {
        if ($settingsObj['hooks'] -and $settingsObj['hooks'].ContainsKey($hookType)) {
            $settingsObj['hooks'][$hookType] = @(
                $settingsObj['hooks'][$hookType] | Where-Object {
                    -not ($_.hooks | Where-Object { $_.command -match 'gitnexus-hook\.cjs' })
                }
            )
        }
    }
    $settingsObj | ConvertTo-Json -Depth 10 | Set-Content $PROJECT_SETTINGS -Encoding UTF8
    ok "Hook entries removed from $PROJECT_SETTINGS"
}

# =============================================================================
step "4/8 -- Restore hooks: .claude\settings.json -> ~\.claude\settings.json"
# =============================================================================
if (-not (Test-Path $PROJECT_SETTINGS)) {
    warn ".claude\settings.json not found -- skipping hook restore"
} else {
    $projSettings = Get-Content $PROJECT_SETTINGS -Raw | ConvertFrom-Json -AsHashtable

    function Get-GitNexusHooks {
        param([hashtable]$settings, [string]$hookType)
        if (-not $settings['hooks'] -or -not $settings['hooks'].ContainsKey($hookType)) { return @() }
        return @($settings['hooks'][$hookType] | Where-Object {
            $_.hooks | Where-Object { $_.command -match 'gitnexus' }
        })
    }

    $gnPreHooks  = Get-GitNexusHooks $projSettings 'PreToolUse'
    $gnPostHooks = Get-GitNexusHooks $projSettings 'PostToolUse'

    if ($gnPreHooks.Count -gt 0 -or $gnPostHooks.Count -gt 0) {
        New-Item -ItemType Directory -Force -Path (Split-Path $GLOBAL_SETTINGS) | Out-Null

        $globalSettings = if (Test-Path $GLOBAL_SETTINGS) {
            Get-Content $GLOBAL_SETTINGS -Raw | ConvertFrom-Json -AsHashtable
        } else { @{} }

        if (-not $globalSettings.ContainsKey('hooks')) { $globalSettings['hooks'] = @{} }

        $existGlobalPre  = if ($globalSettings['hooks']['PreToolUse'])  { @($globalSettings['hooks']['PreToolUse'])  } else { @() }
        $existGlobalPost = if ($globalSettings['hooks']['PostToolUse']) { @($globalSettings['hooks']['PostToolUse']) } else { @() }

        $globalSettings['hooks']['PreToolUse']  = $existGlobalPre  + $gnPreHooks
        $globalSettings['hooks']['PostToolUse'] = $existGlobalPost + $gnPostHooks
        $globalSettings | ConvertTo-Json -Depth 10 | Set-Content $GLOBAL_SETTINGS -Encoding UTF8
        ok "Hooks restored to $GLOBAL_SETTINGS"
    } else {
        warn "No gitnexus hooks in project settings -- nothing to restore"
    }

    # Xoa tat ca gitnexus hooks khoi project settings
    foreach ($hookType in @('PreToolUse', 'PostToolUse')) {
        if ($projSettings['hooks'] -and $projSettings['hooks'].ContainsKey($hookType)) {
            $projSettings['hooks'][$hookType] = @(
                $projSettings['hooks'][$hookType] | Where-Object {
                    -not ($_.hooks | Where-Object { $_.command -match 'gitnexus' })
                }
            )
        }
    }
    $projSettings | ConvertTo-Json -Depth 10 | Set-Content $PROJECT_SETTINGS -Encoding UTF8

    # Neu project settings gio rong thi xoa luon
    $preLeft  = if ($projSettings['hooks']['PreToolUse'])  { @($projSettings['hooks']['PreToolUse']).Count  } else { 0 }
    $postLeft = if ($projSettings['hooks']['PostToolUse']) { @($projSettings['hooks']['PostToolUse']).Count } else { 0 }
    if ($preLeft -eq 0 -and $postLeft -eq 0) {
        Remove-Item -Force $PROJECT_SETTINGS -ErrorAction SilentlyContinue
        ok "Project settings.json empty -- removed"
    }
}

# =============================================================================
step "5/8 -- Restore MCP config: .mcp.json -> ~\.mcp.json"
# =============================================================================
if (-not (Test-Path $PROJECT_MCP)) {
    warn ".mcp.json not found -- skipping MCP restore"
} else {
    $projectMcpObj = Get-Content $PROJECT_MCP -Raw | ConvertFrom-Json -AsHashtable

    if ($projectMcpObj.ContainsKey('mcpServers') -and $projectMcpObj['mcpServers'].ContainsKey('gitnexus')) {
        # Khoi phuc ve global voi command npx (nhu truoc khi install)
        $globalMcpObj = if (Test-Path $GLOBAL_MCP) {
            Get-Content $GLOBAL_MCP -Raw | ConvertFrom-Json -AsHashtable
        } else { @{} }

        if (-not $globalMcpObj.ContainsKey('mcpServers')) { $globalMcpObj['mcpServers'] = @{} }
        $globalMcpObj['mcpServers']['gitnexus'] = @{
            command = "npx"
            args    = @("-y", "gitnexus@1.5.3", "mcp")
        }
        $globalMcpObj | ConvertTo-Json -Depth 10 | Set-Content $GLOBAL_MCP -Encoding UTF8
        ok "gitnexus MCP entry restored to $GLOBAL_MCP"

        # Xoa gitnexus khoi project .mcp.json
        $projectMcpObj['mcpServers'].Remove('gitnexus')
        if ($projectMcpObj['mcpServers'].Count -eq 0) {
            Remove-Item -Force $PROJECT_MCP
            ok "Project .mcp.json empty -- removed"
        } else {
            $projectMcpObj | ConvertTo-Json -Depth 10 | Set-Content $PROJECT_MCP -Encoding UTF8
            ok "gitnexus entry removed from project .mcp.json"
        }
    } else {
        warn "No gitnexus entry in .mcp.json -- skipping"
    }
}

# =============================================================================
step "6/8 -- Remove .gitnexus knowledge graph"
# =============================================================================
if (Test-Path $PROJECT_GITNEXUS) {
    Remove-Item -Recurse -Force $PROJECT_GITNEXUS
    ok "Knowledge graph removed: $PROJECT_GITNEXUS"
} else {
    warn ".gitnexus not found -- already removed or never created"
}

# =============================================================================
step "7/8 -- Remove AGENTS.md + cleanup empty .claude directories"
# =============================================================================
if (Test-Path $AGENTS_MD) {
    Remove-Item -Force $AGENTS_MD
    ok "AGENTS.md removed"
} else {
    warn "AGENTS.md not found -- skipping"
}

# Xoa thu muc hook neu rong
if (Test-Path $PROJECT_HOOK_DIR) {
    $remaining = Get-ChildItem $PROJECT_HOOK_DIR -ErrorAction SilentlyContinue
    if (-not $remaining) {
        Remove-Item -Recurse -Force $PROJECT_HOOK_DIR
        ok "Empty hook directory removed: $PROJECT_HOOK_DIR"
    }
}

# Xoa .claude neu hoan toan rong
if (Test-Path $PROJECT_CLAUDE_DIR) {
    $remaining = Get-ChildItem $PROJECT_CLAUDE_DIR -Recurse -ErrorAction SilentlyContinue
    if (-not $remaining) {
        Remove-Item -Recurse -Force $PROJECT_CLAUDE_DIR
        ok "Empty .claude directory removed"
    } else {
        warn ".claude directory has other content -- kept"
    }
}

# =============================================================================
step "8/8 -- Uninstall gitnexus globally"
# =============================================================================
if (Get-Command gitnexus -ErrorAction SilentlyContinue) {
    npm uninstall -g gitnexus
    if ($LASTEXITCODE -eq 0) {
        ok "gitnexus uninstalled globally"
    } else {
        warn "npm uninstall returned non-zero -- check manually"
    }
} else {
    warn "gitnexus not found in PATH -- already uninstalled"
}

if (Test-Path $GLOBAL_HOOK_DIR)   { Remove-Item -Recurse -Force $GLOBAL_HOOK_DIR;   ok "Global hook directory removed" }
if (Test-Path $GLOBAL_SKILLS_DIR) { Remove-Item -Recurse -Force $GLOBAL_SKILLS_DIR; ok "Global skills directory removed" }

# =============================================================================
Write-Host ""
Write-Host "===============================================" -ForegroundColor Green
Write-Host "  GitNexus uninstall complete!"                 -ForegroundColor Green
Write-Host "===============================================" -ForegroundColor Green
Write-Host ""
Write-Host "  Removed:"                                              -ForegroundColor Cyan
Write-Host "    - <!--gitnexus--> block in CLAUDE.md"               -ForegroundColor Cyan
Write-Host "    - .gitnexus knowledge graph"                        -ForegroundColor Cyan
Write-Host "    - .claude\hooks\gitnexus\gitnexus-hook.cjs"         -ForegroundColor Cyan
Write-Host "    - Project MCP + hook entries"                       -ForegroundColor Cyan
Write-Host "    - AGENTS.md"                                        -ForegroundColor Cyan
Write-Host "    - gitnexus npm global package"                      -ForegroundColor Cyan
Write-Host ""
Write-Host "  Next step: Restart Claude Code to unload MCP server." -ForegroundColor Yellow
Write-Host ""
